-- 3
SELECT DISTINCT s.CITY
FROM STATION s
WHERE s.ID % 2 = 0;

-- 4
SELECT COUNT(s.CITY) - COUNT(DISTINCT s.CITY)
FROM STATION s;

-- 5
(SELECT s.CITY, LENGTH(s.CITY)
FROM STATION s
ORDER BY LENGTH(s.CITY) ASC, s.CITY ASC
LIMIT 1)
UNION
(SELECT s.CITY, LENGTH(s.CITY)
FROM STATION s
ORDER BY LENGTH(s.CITY) DESC, s.CITY ASC
LIMIT 1);

-- 6
-- NOTE: For single char, we can use [aeiou] same as [a|e|i|o|u]
SELECT s.CITY
FROM STATION s
WHERE LEFT(s.CITY,1) REGEXP '[aeiou]';
